#!/usr/bin/env node
import { Argument, Command, CommanderError } from 'commander';
import path from 'path';
import promptSync from 'prompt-sync';
import cel from './lib/cel.js';
import didcel from './lib/didcel.js';

// create the CLI and parse the options
const program = new Command();
program
  .option('-v, --verbose', 'Provide verbose output')
  .parse(process.argv);
const options = program.opts();

// Runs the repl until exit
async function repl({commands}) {
  // configure the REPL
  const prompt = promptSync();
  const repl = new Command();
  let log;
  let didDocument;

  repl.name('command')
    .usage('[options]')
    .exitOverride();

  repl.command('help')
    .description('Show help')
    .action(() => {
      repl.help();
    });

  repl.command('load')
    .description('Load a DID from a cryptographic event log.')
    .action(() => {
      console.error('load not implemented');
    });

  repl.command('create')
    .description('Create a new DID document')
    .action(async () => {
      let result = await didcel.create({curve: 'P-256'});
      didDocument = result.didDocument;
      log = cel.create({data: didDocument});
      console.log('CEL: ', JSON.stringify(log, null, 2));
    });

  repl.command('add')
    .description('Add a verification method or service to the current DID document.')
    .addArgument(new Argument('<property>', 'the name of the property to add to')
      .choices(['authentication', 'assertionMethod', 'capabilityDelegation', 'capabilityInvocation', 'keyAgreement', 'service']))
    .addArgument(new Argument('<type>', 'the type of property to add')
      .choices(['eddsa', 'ecdsa', 'bbs', 'FileService']))
    .action((property, type) => {
      if(property !== 'service' && type === 'ecdsa') {
        const vm = {
          id: '#zDnYeGRG5ehnPAmxcf5mDZpvaerx9CtbPJ1q36T5Ln5wYt3MQ',
          type: 'Multikey',
          controller: didDocument.id,
          publicKeyMultibase: 'zDnYeGRG5ehnPAmxcf5mDZpvaerx9CtbPJ1q36T5Ln5wYt3MQ'
        };
        didDocument.verificationMethod.push(vm);
        didDocument[property].push(vm.id);
      }
      console.log(`add ${property} ${type}: `, JSON.stringify(didDocument, null, 2));
    });

  repl.command('expire')
    .description('Expire a verification method from the current DID document.')
    .argument('<id>', 'the id of the verification method to expire')
    .action(() => {
      console.error('expire not implemented');
    });

  repl.command('remove')
    .description('Remove an object from the current DID document.')
    .argument('<id>', 'the id of the object to remove')
    .action(() => {
      console.error('remove not implemented');
    });

  repl.command('witness')
    .description(
      'Witness the latest set of updates to the DID document.')
    .action(async () => {
      console.error('witnessing not implemented');
    });

  repl.command('save')
    .description(
      'Saves the current DID to a cryptographic event log.')
    .action(async () => {
      console.error('save not implemented');
    });

  repl.command('quit')
    .description('Exit without saving the cryptographic event log.')
    .action(async () => {
      process.exit(0);
    });

  // if command-line commands were provided, run them and exit
  if(commands && commands.length > 0) {
    commands.forEach(async (cmdLine) => {
      let args = cmdLine.split(' ');
      let command = args[0];

      try {
        const commanderArgs = [command, command].concat(args);
        await repl.parseAsync(commanderArgs);
      } catch(err) {
        if(!(err instanceof CommanderError)) {
          throw err;
        }
      }
    });

    process.exit(0);
  }

  // if no command line commands were given, run the repl
  let command = '';
  do {
    const args = prompt('did:cel> ').split(' ');
    command = args[0];

    try {
      const commanderArgs = [command, command].concat(args);
      await repl.parseAsync(commanderArgs);
    } catch(err) {
      // don't automatically exit from the Commander CLI
      if(!(err instanceof CommanderError)) {
        throw err;
      }
    }
  } while(command != 'quit');
}

// Run the repl
await repl({
  commands: options.command
});
