#!/usr/bin/env node
import { Argument, Command, CommanderError } from 'commander';
import cel from './lib/cel.js';
import didcel from './lib/didcel.js';
import promptSync from 'prompt-sync';
import {writeFileSync} from 'fs';
import {createJsonldPrettyPrinter, getObjectByIdSuffix} from './lib/utils.js';

// create the CLI and parse the options
const program = new Command();
program
  .option('-c, --command <command...>', 'One or more commands to execute')
  .option('-v, --verbose', 'Provide verbose output')
  .parse(process.argv);
const options = program.opts();

// create the JSON-LD pretty printer
const jsonldPretty = createJsonldPrettyPrinter({
  preferOrder: ['@context',  '@id', '@type', 'id', 'type', 'cryptosuite',
    'previousEvent']
});

// common properties for a DID Document
const COMMON_PROPERTIES = ['authentication', 'assertionMethod', 'capabilityDelegation', 'capabilityInvocation', 'keyAgreement', 'service'];

// Runs the repl until exit
async function repl({commands}) {
  // configure the REPL
  const prompt = promptSync();
  const repl = new Command();
  let cryptographicEventLog;
  let didDocument;
  let secretKeys = {
    authentication: [],
    assertionMethod: [],
    capabilityInvocation: [],
    capabilityDelegation: [],
    keyAgreement: []
  };

  repl.name('command')
    .usage('[options]')
    .exitOverride();

  repl.command('help')
    .description('Show help')
    .action(() => {
      repl.help();
    });

  repl.command('load')
    .description('Load a DID from a cryptographic event log.')
    .action(() => {
      console.error('load not implemented');
    });

  repl.command('create')
    .description('Create a new DID document')
    .action(async () => {
      let result = await didcel.create({curve: 'P-256'});
      didDocument = result.didDocument;
      secretKeys.assertionMethod = [result.keyPair];
      cryptographicEventLog = cel.create({data: didDocument});
      console.log(`create successful: ${didDocument.id}`);
    });

  repl.command('add')
    .description('Add a verification method or service to the current DID document.')
    .addArgument(new Argument('<property>', 'the name of the property to add to')
      .choices(COMMON_PROPERTIES))
    .addArgument(new Argument('<type>', 'the type of property to add')
      .choices(['eddsa', 'ecdsa', 'bbs', 'FileService']))
    .action(async (property, type) => {
      if(property !== 'service' && type === 'ecdsa') {
        let result = await didcel.addVm(
          {didDocument, verificationRelationship: property, curve: 'P-256'});
        didDocument = result.didDocument;
        secretKeys[property].push(result.keyPair);
        console.log(`added new verification method for ${property}`);
      }
    });

  repl.command('ls')
    .description('list the contents of all identifiers, or a specific one.')
    .addArgument(new Argument('[suffix]', 'the last several characters of the identifier'))
    .action(async (suffix) => {
      console.log(didDocument.id);

      // print detailed object if suffix was provided
      if(suffix) {
        const value = getObjectByIdSuffix({didDocument, suffix});
        if(value) {
          console.log(JSON.stringify(value, jsonldPretty, 2));
          return;
        }
      }

      // summarize DID Document if suffix was not provided
      for(let property of Object.keys(didDocument)) {
        let numEntries = 0;
        if(!Array.isArray(didDocument[property])) {
          continue;
        }
        let propertyListing = `  ${property}: `;
        for(let entry of didDocument[property]) {
          if(typeof entry !== 'object') {
            continue;
          }
          const lastFourOfId =
            entry.id.slice(entry.id.length - 4, entry.id.length);
            propertyListing += entry.type +
              entry.id.slice(0, 4) + '...' + lastFourOfId + ' ';
          numEntries++;
        }
        if(numEntries > 0) {
          console.log(propertyListing);
        }
      }
    });

  repl.command('expire')
    .description('Expire a verification method from the current DID document.')
    .argument('<id>', 'the id of the verification method to expire')
    .action(() => {
      console.error('expire not implemented');
    });

  repl.command('remove')
    .description('Remove an object from the current DID document.')
    .argument('<id>', 'the id of the object to remove')
    .action(() => {
      console.error('remove not implemented');
    });

  repl.command('update')
    .description('Update the cryptographic event log with the latest DID document')
    .action(async () => {
      didDocument = (await didcel.updateProof({didDocument,
        assertionMethod: secretKeys.assertionMethod[0]})).didDocument;
      cryptographicEventLog =
        await cel.update({cel: cryptographicEventLog, data: didDocument});
    });

  repl.command('witness')
    .description(
      'Witness the latest set of updates to the DID document.')
    .action(async () => {
      const proof = await cel.witness({cel: cryptographicEventLog})
      console.log('witness: proofs complete');
    });

  repl.command('save')
    .description(
      'Saves the current DID to a cryptographic event log.')
    .argument('[filename]', 'the name of the file to save the event log to')
    .action(async (filename) => {
      const celFilename = filename || 'did.cel';
      writeFileSync(celFilename, JSON.stringify(cryptographicEventLog, jsonldPretty, 2));
      console.error(`Wrote to ${celFilename}`);
    });

  repl.command('quit')
    .description('Exit without saving the cryptographic event log.')
    .action(async () => {
      process.exit(0);
    });

  // if command-line commands were provided, run them and exit
  if(commands && commands.length > 0) {
    for(const cmdLine of commands) {
      const args = cmdLine.split(' ');
      const command = args[0];
      try {
        const commanderArgs = [command, command].concat(args);
        await repl.parseAsync(commanderArgs);
      } catch(err) {
        if(!(err instanceof CommanderError)) {
          throw err;
        }
      }
    };
  }

  // if no command line commands were given, run the repl
  let command = '';
  do {
    const args = prompt('did:cel> ').split(' ');
    command = args[0];

    try {
      const commanderArgs = [command, command].concat(args);
      await repl.parseAsync(commanderArgs);
    } catch(err) {
      // don't automatically exit from the Commander CLI
      if(!(err instanceof CommanderError)) {
        throw err;
      }
    }
  } while(command != 'quit');
}

// Run the repl
await repl({
  commands: options.command
});
